// Generated by LiveScript 1.3.1
(function(){
  var root, express, path, getsecret, throttle_call, func_cache, bing_api_key, Bing, app, get_image_url, get_image_url_throttled, get_image_url_cached, get_image_url_cached_throttled;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  express = require('express');
  path = require('path');
  getsecret = require('getsecret');
  throttle_call = require('throttle_call');
  func_cache = require('func_cache_mongo')();
  bing_api_key = getsecret('bing_api_key');
  Bing = require('node-bing-api')({
    accKey: bing_api_key
  });
  app = express();
  app.set('port', process.env.PORT || 8080);
  app.use(express['static'](path.join(__dirname, '')));
  app.listen(app.get('port'), '0.0.0.0');
  get_image_url = function(query, callback){
    return Bing.images(query, {}, function(error, res2, body){
      var x;
      return callback((function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = body.d.results).length; i$ < len$; ++i$) {
          x = ref$[i$];
          results$.push(x.MediaUrl);
        }
        return results$;
      }()));
    });
  };
  get_image_url_throttled = throttle_call(get_image_url);
  get_image_url_cached = func_cache(get_image_url);
  get_image_url_cached_throttled = throttle_call(get_image_url_cached);
  app.get('/image', function(req, res){
    return get_image_url_cached_throttled(req.query.name, function(imgurl){
      return res.send(imgurl);
    });
  });
  app.get('/getfeeditems', function(req, res){
    var wordlist, word;
    wordlist = ['cat', 'dog', 'white', 'black', 'blue', 'red', 'bee', 'bird', 'lion', 'tiger', 'fish', 'city', 'house', 'roof', 'tree', 'river', 'apple', 'banana', 'cherry', 'orange', 'pear'];
    return res.json([{
      itemtype: 'example',
      data: {
        foo: 'somefooval',
        bar: 'somebarval'
      },
      social: {
        poster: 'geza'
      }
    }].concat((function(){
      var i$, ref$, len$, results$ = [];
      for (i$ = 0, len$ = (ref$ = wordlist).length; i$ < len$; ++i$) {
        word = ref$[i$];
        results$.push({
          itemtype: 'typeword',
          data: {
            word: word
          },
          social: {
            poster: 'someuser'
          }
        });
      }
      return results$;
    }())));
  });
}).call(this);
