// Generated by LiveScript 1.3.1
(function(){
  var root, express, path, getsecret, throttle_call, request, func_cache, bing_api_key, Bing, app, get_binary_content, get_binary_content_as_base64, get_binary_content_as_base64_cached, get_image_url, get_image_url_throttled, get_image_url_cached, get_image_url_cached_throttled, get_imagedata_by_name, get_imagedata_by_name_cached;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  express = require('express');
  path = require('path');
  getsecret = require('getsecret');
  throttle_call = require('throttle_call');
  request = require('request');
  func_cache = require('func_cache_mongo')();
  bing_api_key = getsecret('bing_api_key');
  Bing = require('node-bing-api')({
    accKey: bing_api_key
  });
  app = express();
  app.set('port', process.env.PORT || 8080);
  app.use(express['static'](path.join(__dirname, 'public')));
  app.listen(app.get('port'), '0.0.0.0');
  get_binary_content = function(url, callback){
    return request({
      url: url,
      encoding: null
    }, function(err, response, data){
      var content_type;
      content_type = response.headers['content-type'];
      return callback(data, content_type);
    });
  };
  get_binary_content_as_base64 = function(url, callback){
    console.log('get_binary_content_as_base64: ' + url);
    return get_binary_content(url, function(data, content_type){
      var encoded_content;
      encoded_content = new Buffer(data).toString('base64');
      return callback("data:" + content_type + ";base64," + encoded_content);
    });
  };
  get_binary_content_as_base64_cached = func_cache(get_binary_content_as_base64, 'get_binary_content_as_base64');
  app.get('/proxybase64', function(req, res){
    var url;
    url = req.query.url;
    if (url == null) {
      res.send('need url');
      return;
    }
    return get_binary_content_as_base64_cached(url, function(data){
      return res.send(data);
    });
  });
  app.get('/proxy', function(req, res){
    var url;
    url = req.query.url;
    if (url == null) {
      res.send('need url');
      return;
    }
    return get_binary_content(url, function(data, content_type){
      res.setHeader('Content-Type', content_type);
      return res.send(data);
    });
  });
  get_image_url = function(query, callback){
    return Bing.images(query, {}, function(error, res2, body){
      var x;
      return callback((function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = body.d.results).length; i$ < len$; ++i$) {
          x = ref$[i$];
          results$.push(x.MediaUrl);
        }
        return results$;
      }()));
    });
  };
  get_image_url_throttled = throttle_call(get_image_url);
  get_image_url_cached = func_cache(get_image_url, 'get_image_url');
  get_image_url_cached_throttled = throttle_call(get_image_url_cached);
  app.get('/image', function(req, res){
    if (req.query.name == null) {
      res.send('mising name parameter');
      return;
    }
    return get_image_url_cached_throttled(req.query.name, function(imgurl){
      return res.send(imgurl);
    });
  });
  get_imagedata_by_name = function(query, callback){
    return get_image_url(query, function(imgurls){
      var imgurl;
      imgurl = imgurls[0];
      return get_binary_content_as_base64_cached(imgurl, function(imgdata){
        return callback(imgdata);
      });
    });
  };
  get_imagedata_by_name_cached = func_cache(get_imagedata_by_name, 'get_imagedata_by_name');
  app.get('/imagedatabyname', function(req, res){
    if (req.query.name == null) {
      res.send('mising name parameter');
      return;
    }
    return get_imagedata_by_name_cached(req.query.name, function(imgdata){
      return res.send(imgdata);
    });
  });
  app.get('/getfeeditems', function(req, res){
    var wordlist, word;
    wordlist = ['cat', 'dog', 'white', 'black', 'blue', 'red', 'bee', 'bird', 'lion', 'tiger', 'fish', 'city', 'house', 'roof', 'tree', 'river', 'apple', 'banana', 'cherry', 'orange', 'pear'];
    return res.json([{
      itemtype: 'example',
      data: {
        foo: 'somefooval',
        bar: 'somebarval'
      },
      social: {
        poster: 'geza'
      }
    }].concat((function(){
      var i$, ref$, len$, results$ = [];
      for (i$ = 0, len$ = (ref$ = wordlist).length; i$ < len$; ++i$) {
        word = ref$[i$];
        results$.push({
          itemtype: 'typeword',
          data: {
            word: word
          },
          social: {
            poster: 'someuser'
          }
        });
      }
      return results$;
    }())));
  });
}).call(this);
