// Generated by LiveScript 1.3.1
(function(){
  var itemtypes, out$ = typeof exports != 'undefined' && exports || this;
  out$.itemtypes = itemtypes = {
    typeword: {
      thumbnail: 'typeword-thumbnail',
      activity: 'typeword-activity'
    }
  };
}).call(this);
