// Generated by LiveScript 1.3.1
(function(){
  var makeActivity, makeThumbnail, itemtypes, out$ = typeof exports != 'undefined' && exports || this;
  out$.makeActivity = makeActivity = function(item){
    var itemtype, activity, output, k, v;
    itemtype = item.itemtype;
    activity = itemtypes[itemtype].activity;
    if (activity == null) {
      activity = itemtype + '-activity';
    }
    output = $("<" + activity + ">");
    for (k in item) {
      v = item[k];
      output.prop(k, v);
    }
    return output;
  };
  out$.makeThumbnail = makeThumbnail = function(item){
    var itemtype, thumbnail, output, k, v;
    itemtype = item.itemtype;
    thumbnail = itemtypes[itemtype].thumbnail;
    if (thumbnail == null) {
      thumbnail = itemtype + '-thumbnail';
    }
    output = $("<" + thumbnail + ">");
    for (k in item) {
      v = item[k];
      output.prop(k, v);
    }
    return output;
  };
  out$.itemtypes = itemtypes = {
    typeword: {
      thumbnail: 'typeword-thumbnail',
      activity: 'typeword-activity'
    },
    example: {
      thumbnail: 'example-thumbnail',
      activity: 'example-activity'
    }
  };
}).call(this);
