// Generated by LiveScript 1.3.1
(function(){
  var fs, async, couchdb_url, nano, origServer, replicateServer, main;
  fs = require('fs');
  async = require('async');
  couchdb_url = require('../couchdb_utils').couchdb_url;
  nano = require('nano')(couchdb_url);
  origServer = '';
  replicateServer = '';
  main = function(){
    if (!fs.existsSync('www')) {
      console.log('you need to run this script from the edufeed directory');
      return;
    }
    if (origServer === '' || replicateServer === '') {
      console.log('you need to specify the original and/or replicate couchdb server names in the script');
    }
    return nano.db.list(function(err, dblist){
      if (err != null) {
        console.log('error occurred while listing databases');
        console.log(err);
        return;
      }
      return async.eachSeries(dblist, function(dbname, ncallback){
        var i, username, origdb, replicatedb;
        console.log('replicating ' + dbname);
        i = dbname.indexOf('_');
        username = dbname.slice(i + 1, dbname.length);
        origdb = 'http://' + username + ':' + username + '@' + origServer + '.cloudant.com/' + dbname;
        replicatedb = 'http://' + username + ':' + username + '@' + replicateServer + '.cloudant.com/' + dbname;
        return nano.db.replicate(origdb, replicatedb, function(){
          return ncallback(null, null);
        });
      }, function(){
        console.log('done replicating all databases');
        return process.exit();
      });
    });
  };
  main();
}).call(this);
